// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import org.xebia.conference.view.gwt.client.managed.activity.SpeakerEditActivityWrapper.View;
import org.xebia.conference.view.gwt.client.managed.request.ApplicationRequestFactory;
import org.xebia.conference.view.gwt.client.managed.ui.TalkSetEditor;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;
import org.xebia.conference.view.gwt.client.scaffold.activity.IsScaffoldMobileActivity;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyEditView;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyListPlace;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyPlace;

public abstract class SpeakerEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setTalksPickerValues(Collections.<TalkProxy>emptyList());
        requests.talkRequest().findTalkEntries(0, 50).with(org.xebia.conference.view.gwt.client.managed.ui.TalkProxyRenderer.instance().getPaths()).fire(new Receiver<List<TalkProxy>>() {

            public void onSuccess(List<TalkProxy> response) {
                List<TalkProxy> values = new ArrayList<TalkProxy>();
                values.add(null);
                values.addAll(response);
                view.setTalksPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }
}
