// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import java.util.List;
import java.util.Set;
import org.xebia.conference.view.gwt.client.managed.request.ApplicationRequestFactory;
import org.xebia.conference.view.gwt.client.managed.ui.TalkSetEditor;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;
import org.xebia.conference.view.gwt.client.scaffold.ScaffoldMobileApp;
import org.xebia.conference.view.gwt.client.scaffold.activity.IsScaffoldMobileActivity;
import org.xebia.conference.view.gwt.client.scaffold.place.AbstractProxyListActivity;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyListView;

public abstract class SpeakerListActivity_Roo_Gwt extends AbstractProxyListActivity<SpeakerProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public SpeakerListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<org.xebia.conference.view.gwt.client.proxy.SpeakerProxy> view, Class<org.xebia.conference.view.gwt.client.proxy.SpeakerProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.speakerRequest().countAllSpeakers().fire(callback);
    }
}
