// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.xebia.conference.view.gwt.client.managed.request.ApplicationRequestFactory;
import org.xebia.conference.view.gwt.client.managed.ui.TalkDetailsView;
import org.xebia.conference.view.gwt.client.managed.ui.TalkEditView;
import org.xebia.conference.view.gwt.client.managed.ui.TalkListView;
import org.xebia.conference.view.gwt.client.managed.ui.TalkMobileDetailsView;
import org.xebia.conference.view.gwt.client.managed.ui.TalkMobileEditView;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;
import org.xebia.conference.view.gwt.client.request.TalkRequest;
import org.xebia.conference.view.gwt.client.scaffold.ScaffoldApp;
import org.xebia.conference.view.gwt.client.scaffold.place.CreateAndEditProxy;
import org.xebia.conference.view.gwt.client.scaffold.place.FindAndEditProxy;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyPlace;

public abstract class TalkActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        TalkEditView.instance().setCreating(true);
        final TalkRequest request = requests.talkRequest();
        Activity activity = new CreateAndEditProxy<TalkProxy>(TalkProxy.class, request, ScaffoldApp.isMobile() ? TalkMobileEditView.instance() : TalkEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(TalkProxy proxy) {
                request.saveTalk(proxy);
                return request;
            }
        };
        return new TalkEditActivityWrapper(requests, ScaffoldApp.isMobile() ? TalkMobileEditView.instance() : TalkEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<org.xebia.conference.view.gwt.client.proxy.TalkProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<TalkProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        TalkEditView.instance().setCreating(false);
        EntityProxyId<TalkProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<TalkProxy>(proxyId, requests, ScaffoldApp.isMobile() ? TalkMobileEditView.instance() : TalkEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(TalkProxy proxy) {
                TalkRequest request = requests.talkRequest();
                request.saveTalk(proxy);
                return request;
            }
        };
        return new TalkEditActivityWrapper(requests, ScaffoldApp.isMobile() ? TalkMobileEditView.instance() : TalkEditView.instance(), activity, proxyId);
    }
}
