// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import java.util.List;
import org.xebia.conference.view.gwt.client.managed.request.ApplicationRequestFactory;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;
import org.xebia.conference.view.gwt.client.scaffold.ScaffoldMobileApp;
import org.xebia.conference.view.gwt.client.scaffold.activity.IsScaffoldMobileActivity;
import org.xebia.conference.view.gwt.client.scaffold.place.AbstractProxyListActivity;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyListView;

public abstract class TalkListActivity_Roo_Gwt extends AbstractProxyListActivity<TalkProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public TalkListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<org.xebia.conference.view.gwt.client.proxy.TalkProxy> view, Class<org.xebia.conference.view.gwt.client.proxy.TalkProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.talkRequest().countAllTalks().fire(callback);
    }
}
