// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.xebia.conference.view.gwt.client.managed.activity.TalkEditActivityWrapper.View;
import org.xebia.conference.view.gwt.client.managed.request.ApplicationRequestFactory;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;
import org.xebia.conference.view.gwt.client.scaffold.activity.IsScaffoldMobileActivity;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyEditView;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyListPlace;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyPlace;

public abstract class TalkEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setSpeakerPickerValues(Collections.<SpeakerProxy>emptyList());
        requests.speakerRequest().findSpeakerEntries(0, 50).with(org.xebia.conference.view.gwt.client.managed.ui.SpeakerProxyRenderer.instance().getPaths()).fire(new Receiver<List<SpeakerProxy>>() {

            public void onSuccess(List<SpeakerProxy> response) {
                List<SpeakerProxy> values = new ArrayList<SpeakerProxy>();
                values.add(null);
                values.addAll(response);
                view.setSpeakerPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }
}
