// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;
import org.xebia.conference.view.gwt.client.scaffold.place.ProxyDetailsView;

public abstract class SpeakerMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<SpeakerProxy> {

    @UiField
    Element id;

    @UiField
    Element firstname;

    @UiField
    Element lastname;

    @UiField
    Element email;

    @UiField
    Element organization;

    @UiField
    Element birthdate;

    @UiField
    Element age;

    @UiField
    Element created;

    @UiField
    Element talks;

    @UiField
    Element version;

    SpeakerProxy proxy;

    public void setValue(SpeakerProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        firstname.setInnerText(proxy.getFirstname() == null ? "" : String.valueOf(proxy.getFirstname()));
        lastname.setInnerText(proxy.getLastname() == null ? "" : String.valueOf(proxy.getLastname()));
        email.setInnerText(proxy.getEmail() == null ? "" : String.valueOf(proxy.getEmail()));
        organization.setInnerText(proxy.getOrganization() == null ? "" : String.valueOf(proxy.getOrganization()));
        birthdate.setInnerText(proxy.getBirthdate() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getBirthdate()));
        age.setInnerText(proxy.getAge() == null ? "" : String.valueOf(proxy.getAge()));
        created.setInnerText(proxy.getCreated() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getCreated()));
        talks.setInnerText(proxy.getTalks() == null ? "" : org.xebia.conference.view.gwt.client.scaffold.place.CollectionRenderer.of(org.xebia.conference.view.gwt.client.managed.ui.TalkProxyRenderer.instance()).render(proxy.getTalks()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
