// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.request;

import org.xebia.conference.view.gwt.client.request.SpeakerRequest;
import org.xebia.conference.view.gwt.client.request.TalkRequest;
import org.xebia.conference.view.gwt.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    SpeakerRequest speakerRequest();

    TalkRequest talkRequest();
}
