// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.xebia.conference.view.gwt.client.managed.request;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import org.xebia.conference.view.gwt.client.proxy.SpeakerProxy;
import org.xebia.conference.view.gwt.client.proxy.TalkProxy;

public abstract class ApplicationEntityTypesProcessor<T> {

    private final T defaultValue;

    private T result;

    public ApplicationEntityTypesProcessor() {
        defaultValue = null;
    }

    public ApplicationEntityTypesProcessor(T defaultValue) {
        this.defaultValue = defaultValue;
    }

    public static Set<java.lang.Class<? extends com.google.web.bindery.requestfactory.shared.EntityProxy>> getAll() {
        Set<Class<? extends EntityProxy>> rtn = new HashSet<Class<? extends EntityProxy>>();
        rtn.add(SpeakerProxy.class);
        rtn.add(TalkProxy.class);
        return Collections.unmodifiableSet(rtn);
    }

    private static void process(org.xebia.conference.view.gwt.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Class<?> clazz) {
        if (SpeakerProxy.class.equals(clazz)) {
            processor.handleSpeaker((SpeakerProxy) null);
            return;
        }
        if (TalkProxy.class.equals(clazz)) {
            processor.handleTalk((TalkProxy) null);
            return;
        }
        processor.handleNonProxy(null);
    }

    private static void process(org.xebia.conference.view.gwt.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Object proxy) {
        if (proxy instanceof SpeakerProxy) {
            processor.handleSpeaker((SpeakerProxy) proxy);
            return;
        }
        if (proxy instanceof TalkProxy) {
            processor.handleTalk((TalkProxy) proxy);
            return;
        }
        processor.handleNonProxy(proxy);
    }

    public void handleNonProxy(Object object) {
    }

    public abstract void handleSpeaker(SpeakerProxy proxy);

    public abstract void handleTalk(TalkProxy proxy);

    public T process(Class<?> clazz) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, clazz);
        return result;
    }

    public T process(Object proxy) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, proxy);
        return result;
    }

    protected void setResult(T result) {
        this.result = result;
    }
}
